name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install requirements
        run: pip install coverage
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "100"
      - name: Tests
        run: coverage run -m unittest discover -s tests -p '*.py'
      - name: Tests coverage
        run: coverage report
      - name: Tests coverage branch
        run: pytest --cov tests --cov-branch --cov-report term-missing

